/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as InstallRouteImport } from './routes/install'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as OwnerIndexRouteImport } from './routes/$owner/index'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner/$repo/settings'
import { Route as OwnerSettingsBillingRouteImport } from './routes/$owner/settings/billing'
import { Route as OwnerSettingsMembersRouteImport } from './routes/$owner/settings/members'
import { Route as OwnerRepoBaselinesIndexRouteImport } from './routes/$owner/$repo/baselines/index'
import { Route as OwnerRepoBaselinesSplatRouteImport } from './routes/$owner/$repo/baselines/$'
import { Route as OwnerRepoBuildsNumberRouteImport } from './routes/$owner/$repo/builds/$number'
import { Route as OwnerRepoBuildsNumberIndexRouteImport } from './routes/$owner/$repo/builds/$number/index'
import { Route as OwnerRepoBuildsNumberSnapshotsSnapshotIdRouteImport } from './routes/$owner/$repo/builds/$number/snapshots/$snapshotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/$owner/$repo/settings',
  path: '/$owner/$repo/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsBillingRoute = OwnerSettingsBillingRouteImport.update({
  id: '/$owner/settings/billing',
  path: '/$owner/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsMembersRoute = OwnerSettingsMembersRouteImport.update({
  id: '/$owner/settings/members',
  path: '/$owner/settings/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoBaselinesIndexRoute = OwnerRepoBaselinesIndexRouteImport.update({
  id: '/$owner/$repo/baselines/',
  path: '/$owner/$repo/baselines/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoBaselinesSplatRoute = OwnerRepoBaselinesSplatRouteImport.update({
  id: '/$owner/$repo/baselines/$',
  path: '/$owner/$repo/baselines/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoBuildsNumberRoute = OwnerRepoBuildsNumberRouteImport.update({
  id: '/$owner/$repo/builds/$number',
  path: '/$owner/$repo/builds/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoBuildsNumberIndexRoute =
  OwnerRepoBuildsNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OwnerRepoBuildsNumberRoute,
  } as any)
const OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute =
  OwnerRepoBuildsNumberSnapshotsSnapshotIdRouteImport.update({
    id: '/snapshots/$snapshotId',
    path: '/snapshots/$snapshotId',
    getParentRoute: () => OwnerRepoBuildsNumberRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/install': typeof InstallRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/settings/billing': typeof OwnerSettingsBillingRoute
  '/$owner/settings/members': typeof OwnerSettingsMembersRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/baselines/$': typeof OwnerRepoBaselinesSplatRoute
  '/$owner/$repo/builds/$number': typeof OwnerRepoBuildsNumberRouteWithChildren
  '/$owner/$repo/baselines/': typeof OwnerRepoBaselinesIndexRoute
  '/$owner/$repo/builds/$number/': typeof OwnerRepoBuildsNumberIndexRoute
  '/$owner/$repo/builds/$number/snapshots/$snapshotId': typeof OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/install': typeof InstallRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/settings/billing': typeof OwnerSettingsBillingRoute
  '/$owner/settings/members': typeof OwnerSettingsMembersRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/baselines/$': typeof OwnerRepoBaselinesSplatRoute
  '/$owner/$repo/baselines': typeof OwnerRepoBaselinesIndexRoute
  '/$owner/$repo/builds/$number': typeof OwnerRepoBuildsNumberIndexRoute
  '/$owner/$repo/builds/$number/snapshots/$snapshotId': typeof OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/install': typeof InstallRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/settings/billing': typeof OwnerSettingsBillingRoute
  '/$owner/settings/members': typeof OwnerSettingsMembersRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/baselines/$': typeof OwnerRepoBaselinesSplatRoute
  '/$owner/$repo/builds/$number': typeof OwnerRepoBuildsNumberRouteWithChildren
  '/$owner/$repo/baselines/': typeof OwnerRepoBaselinesIndexRoute
  '/$owner/$repo/builds/$number/': typeof OwnerRepoBuildsNumberIndexRoute
  '/$owner/$repo/builds/$number/snapshots/$snapshotId': typeof OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/install'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/$owner/'
    | '/$owner/$repo/settings'
    | '/$owner/settings/billing'
    | '/$owner/settings/members'
    | '/$owner/$repo/'
    | '/$owner/$repo/baselines/$'
    | '/$owner/$repo/builds/$number'
    | '/$owner/$repo/baselines/'
    | '/$owner/$repo/builds/$number/'
    | '/$owner/$repo/builds/$number/snapshots/$snapshotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/install'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/$owner'
    | '/$owner/$repo/settings'
    | '/$owner/settings/billing'
    | '/$owner/settings/members'
    | '/$owner/$repo'
    | '/$owner/$repo/baselines/$'
    | '/$owner/$repo/baselines'
    | '/$owner/$repo/builds/$number'
    | '/$owner/$repo/builds/$number/snapshots/$snapshotId'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/install'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/$owner/'
    | '/$owner/$repo/settings'
    | '/$owner/settings/billing'
    | '/$owner/settings/members'
    | '/$owner/$repo/'
    | '/$owner/$repo/baselines/$'
    | '/$owner/$repo/builds/$number'
    | '/$owner/$repo/baselines/'
    | '/$owner/$repo/builds/$number/'
    | '/$owner/$repo/builds/$number/snapshots/$snapshotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  InstallRoute: typeof InstallRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRoute
  OwnerSettingsBillingRoute: typeof OwnerSettingsBillingRoute
  OwnerSettingsMembersRoute: typeof OwnerSettingsMembersRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoBaselinesSplatRoute: typeof OwnerRepoBaselinesSplatRoute
  OwnerRepoBuildsNumberRoute: typeof OwnerRepoBuildsNumberRouteWithChildren
  OwnerRepoBaselinesIndexRoute: typeof OwnerRepoBaselinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/$owner'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/$owner/$repo/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/settings/billing': {
      id: '/$owner/settings/billing'
      path: '/$owner/settings/billing'
      fullPath: '/$owner/settings/billing'
      preLoaderRoute: typeof OwnerSettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/settings/members': {
      id: '/$owner/settings/members'
      path: '/$owner/settings/members'
      fullPath: '/$owner/settings/members'
      preLoaderRoute: typeof OwnerSettingsMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/baselines/': {
      id: '/$owner/$repo/baselines/'
      path: '/$owner/$repo/baselines'
      fullPath: '/$owner/$repo/baselines/'
      preLoaderRoute: typeof OwnerRepoBaselinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/baselines/$': {
      id: '/$owner/$repo/baselines/$'
      path: '/$owner/$repo/baselines/$'
      fullPath: '/$owner/$repo/baselines/$'
      preLoaderRoute: typeof OwnerRepoBaselinesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/builds/$number': {
      id: '/$owner/$repo/builds/$number'
      path: '/$owner/$repo/builds/$number'
      fullPath: '/$owner/$repo/builds/$number'
      preLoaderRoute: typeof OwnerRepoBuildsNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/builds/$number/': {
      id: '/$owner/$repo/builds/$number/'
      path: '/'
      fullPath: '/$owner/$repo/builds/$number/'
      preLoaderRoute: typeof OwnerRepoBuildsNumberIndexRouteImport
      parentRoute: typeof OwnerRepoBuildsNumberRoute
    }
    '/$owner/$repo/builds/$number/snapshots/$snapshotId': {
      id: '/$owner/$repo/builds/$number/snapshots/$snapshotId'
      path: '/snapshots/$snapshotId'
      fullPath: '/$owner/$repo/builds/$number/snapshots/$snapshotId'
      preLoaderRoute: typeof OwnerRepoBuildsNumberSnapshotsSnapshotIdRouteImport
      parentRoute: typeof OwnerRepoBuildsNumberRoute
    }
  }
}

interface OwnerRepoBuildsNumberRouteChildren {
  OwnerRepoBuildsNumberIndexRoute: typeof OwnerRepoBuildsNumberIndexRoute
  OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute: typeof OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute
}

const OwnerRepoBuildsNumberRouteChildren: OwnerRepoBuildsNumberRouteChildren = {
  OwnerRepoBuildsNumberIndexRoute: OwnerRepoBuildsNumberIndexRoute,
  OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute:
    OwnerRepoBuildsNumberSnapshotsSnapshotIdRoute,
}

const OwnerRepoBuildsNumberRouteWithChildren =
  OwnerRepoBuildsNumberRoute._addFileChildren(
    OwnerRepoBuildsNumberRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  InstallRoute: InstallRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRoute,
  OwnerSettingsBillingRoute: OwnerSettingsBillingRoute,
  OwnerSettingsMembersRoute: OwnerSettingsMembersRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoBaselinesSplatRoute: OwnerRepoBaselinesSplatRoute,
  OwnerRepoBuildsNumberRoute: OwnerRepoBuildsNumberRouteWithChildren,
  OwnerRepoBaselinesIndexRoute: OwnerRepoBaselinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
